name: docker-build:openvino

on:
  push:
    branches: master

jobs:
  build-n-push-openvino:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Cache docker 
        uses: actions/cache@v2
        env:
          cache-name: cache-docker-lib-openvino
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: /var/lib/docker/
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/openvino/
          file: docker/openvino/Dockerfile
          platforms: linux/amd64
          push: true
          tags: intelpengo/openvino